### ISSUE TITLE
Loading specific routes broken?

### ISSUE THREAD

**Issue by nullbio** [simonh1000/elm-webpack-starter#12]
Hi. Thanks for sharing this. I noticed in your webpack.config.js you have:

```
add: (app, middleware, options) => {
  app.use(history());
}
```

Unless I'm missing something, this doesn't seem to work for loading specific routes because it doesn't root the index.js file at "/", i.e. you get this in the console:

Try to navigate to: `http://localhost:3000/profile/bob`
HTML output script tag: 	`<script type="text/javascript" src="index.js"></script>`
Console error: `GET http://localhost:3000/profile/index.js 404 (Not Found)`

As you can see, it's because it's referring to "index.js" from /profile/bob instead of "/index.js"

Is this something you're aware of, or am I missing something? It's possible I'm missing some of your code as well, as I didn't keep 100% of it.

For now I've resorted to removing `inject: "body"` and hardcoding the script tag inclusion in my index.html in the body section.

**Comment by simonh1000** [comment]
If you have any spare cycles to try the history branch that would be appreciated

**Comment by nullbio** [comment]
That did the trick! Thank you :).
