### ISSUE TITLE
Babel 7

### ISSUE THREAD

**Issue by vicver82** [simonh1000/elm-webpack-starter#13]
Hi!
Thank you for your work. I think this is a great starting point for a Webpack-based Elm app!

I see that the Babel core version in the `package.json` file is still `^6.x.x`, which is confusing because the Readme file states that Babel 7 is used for JS transpilation.

Am I missing something or is this a mistake?
I can help with the Babel 7 upgrade if you wish.

Thank you.

**Comment by simonh1000** [comment]
PRs very welcome - I suspect that 7 should work ok easily enough as we're not doing anything special
