### ISSUE TITLE
Missing exclude in webpack.config.js, or intended?

### ISSUE THREAD

**Issue by nullbio** [simonh1000/elm-webpack-starter#19]
Heya @simonh1000 -- Just noticed there's a missing exclude line here (no elm-stuff and node_modules exclude):

https://github.com/simonh1000/elm-webpack-starter/blob/master/webpack.config.js#L73

Just wondering if this was intended?

Thanks!

**Comment by simonh1000** [comment]
Thanks :-)
Indeed, it probably should have the same exclude - did it cause you issues or is it just an observation.

**Comment by nullbio** [comment]
Didn't cause me any issues, just noticed it :-)
