### ISSUE TITLE
No colors in error log

### ISSUE THREAD

**Issue by janwirth** [simonh1000/elm-webpack-starter#3]
Colors are missing from error reports
![image](https://user-images.githubusercontent.com/7485959/32420435-8a1f67a4-c28a-11e7-880e-5f3941eca8be.png)

With elm-webpack-starter from the elm community 
![image](https://user-images.githubusercontent.com/7485959/32420445-b214ceb6-c28a-11e7-8f9b-f1a63f0630aa.png)

**Comment by simonh1000** [comment]
Thanks for this but I don't think I'll be able to get round to it in the short term. If you want to submit A pr feel free

**Comment by janwirth** [comment]
Do you know where to start

**Comment by simonh1000** [comment]
I found a way to do this 
![screen shot 2018-03-25 at 13 56 44](https://user-images.githubusercontent.com/5256724/37874699-638a40ec-3034-11e8-9623-aa415cf7fff3.png)

**Comment by janwirth** [comment]
I built my own template - latest webpack etc :)
https://github.com/FranzSkuffka/elm-webpack-starter-kid
