### ISSUE TITLE
CSS assets are not optimised/minified in production mode

### ISSUE THREAD

**Issue by mickeyvip** [simonh1000/elm-webpack-starter#30]
When running 

```$ npm run prod``` 

one would expect the `.css` assets to be minified, but `mini-css-extract-plugin` does not minify the `.css`.

The `optimize-css-assets-webpack-plugin` (https://github.com/NMFR/optimize-css-assets-webpack-plugin) can be used as described in 
https://webpack.js.org/plugins/mini-css-extract-plugin/#minimizing-for-production.

**Comment by simonh1000** [comment]
sorry! let me know if https://github.com/simonh1000/elm-webpack-starter/pull/33 works for you
