### ISSUE TITLE
Elmx seems hard to add

### ISSUE THREAD

**Issue by hickscorp** [simonh1000/elm-webpack-starter#4]
This is not really an issue, more like an enhancement request.

How would one add `elmx-webpack-preloader` to the webpack config? I gave up after numerous attempts. Would there be a way to have `.elmx` support in this great boilerplate project?

**Comment by simonh1000** [comment]
Sorry, i have no idea as I've never used elmx

**Comment by hickscorp** [comment]
Understood. I'll post updates if I'm ever able to add Elmx to this boilerplate.
Thanks!
