### ISSUE TITLE
Questions about some of the dependencies

### ISSUE THREAD

**Issue by larribas** [simonh1000/elm-webpack-starter#7]
Hello,

I was going through the `package.json` file to understand the dependencies and there are a couple of questions I had. Maybe there will be people sharing the same questions:

1. I don't see the `chokidar-cli` dependency being used explicitly by webpack  or the code. My understanding from what it says [in its README](https://github.com/kimmobrunfeldt/chokidar-cli) is that webpack will use it if available, right?

2. I see a `postcss-loader` but I don't see it used explicitly either. Is any other loader using that under the hood?

**Comment by simonh1000** [comment]
Good catches. Chokidar was something I added at a time when elm test was not monitoring changes in source code. That's changed now and should be removed.

Postcss is not used either

I'll remove both when i get a moment
