### ISSUE TITLE
How to use ports?

### ISSUE THREAD

**Issue by dfcarpenter** [simonh1000/elm-webpack-starter#9]
I'm somewhat of a beginner but how would I use ports in dev with this? I notice that the webpack html plugin injects the script into the body but with ports it seems you need something like `var app = Elm.Main.Fullscreen` and then `app.ports.myPort...`

**Comment by simonh1000** [comment]
I have something like the following in one of my index.js
```
    var Elm = require("./Main");
    app = Elm.Main.fullscreen(flags);

    app.ports.toJs.subscribe(data => {
   ...
    }
```

Does that help?

**Comment by dfcarpenter** [comment]
Yes, thanks!

**Comment by simonh1000** [comment]
Im going to add a specific example of ports with the next release
